/*
 * ExtProgSwingGUI.java
 *
 * Created on December 1, 2004, 9:10 PM
 */

package anecho.JamochaMUD;

/**
 *
 * @author Jeff Robinson
 */
public class ExtProgSwingGUI extends javax.swing.JDialog {
    
    /**
     * Creates new form ExtProgSwingGUI
     * @param parent 
     * @param modal 
     */
    public ExtProgSwingGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        browserLabel = new javax.swing.JLabel();
        instanceCB = new javax.swing.JCheckBox();
        browserTF = new javax.swing.JTextField();
        browserButton = new javax.swing.JButton();
        imageTF = new javax.swing.JTextField();
        imageButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        ftpLabel = new javax.swing.JLabel();
        ftpTF = new javax.swing.JTextField();
        ftpButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        emailButton = new javax.swing.JButton();
        okayButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("anecho/JamochaMUD/JamochaMUDBundle"); // NOI18N
        setTitle(bundle.getString("External_Programs")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        browserLabel.setText(bundle.getString("FTP_Client")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 3, 3);
        getContentPane().add(browserLabel, gridBagConstraints);

        instanceCB.setSelected(true);
        instanceCB.setText(bundle.getString("FTP_Client")); // NOI18N
        instanceCB.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 3, 7);
        getContentPane().add(instanceCB, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(browserTF, gridBagConstraints);

        browserButton.setText(bundle.getString("FTP_Client")); // NOI18N
        browserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 7);
        getContentPane().add(browserButton, gridBagConstraints);

        imageTF.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(imageTF, gridBagConstraints);

        imageButton.setText(bundle.getString("ExtProgSwingGUI.imageButton.text")); // NOI18N
        imageButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 7);
        getContentPane().add(imageButton, gridBagConstraints);

        imageLabel.setText(bundle.getString("FTP_Client")); // NOI18N
        imageLabel.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(imageLabel, gridBagConstraints);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText(bundle.getString("FTP_Client")); // NOI18N
        jCheckBox1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 7);
        getContentPane().add(jCheckBox1, gridBagConstraints);

        ftpLabel.setText(bundle.getString("FTP_Client")); // NOI18N
        ftpLabel.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(ftpLabel, gridBagConstraints);

        ftpTF.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(ftpTF, gridBagConstraints);

        ftpButton.setText(bundle.getString("FTP_Client")); // NOI18N
        ftpButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 7);
        getContentPane().add(ftpButton, gridBagConstraints);

        emailLabel.setText(bundle.getString("FTP_Client")); // NOI18N
        emailLabel.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(emailLabel, gridBagConstraints);

        emailTF.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 3, 3);
        getContentPane().add(emailTF, gridBagConstraints);

        emailButton.setText(bundle.getString("FTP_Client")); // NOI18N
        emailButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 7);
        getContentPane().add(emailButton, gridBagConstraints);

        okayButton.setText(bundle.getString("FTP_Client")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 3);
        getContentPane().add(okayButton, gridBagConstraints);

        cancelButton.setText(bundle.getString("FTP_Client")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(7, 3, 7, 7);
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserButtonActionPerformed
        final javax.swing.JFileChooser jfc = new javax.swing.JFileChooser();
        if (!browserTF.getText().equals("")) {
            final java.io.File current = new java.io.File(browserTF.getText());
            jfc.setSelectedFile(current);
        }
        jfc.setVisible(true);
    }//GEN-LAST:event_browserButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browserButton;
    private javax.swing.JLabel browserLabel;
    private javax.swing.JTextField browserTF;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton emailButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton ftpButton;
    private javax.swing.JLabel ftpLabel;
    private javax.swing.JTextField ftpTF;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField imageTF;
    private javax.swing.JCheckBox instanceCB;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton okayButton;
    // End of variables declaration//GEN-END:variables
    
}
