{
s/JazzySpellLevel/beta1/g
s/JazzySpellVersion/04-01-24/g
s/JMUDWPIVersion/04\\01\\24/g
s/GUIWPIVersion/GUIWPIVER/g
s/EXTRANETWPIVersion/EXTRANETWPIVER/g
s/LEGACYWPIVersion/LEGACYWPIVER/g
s/PACKARCHIVEPATH/f:\\programming/g
s/JAZZYCORE/F:\\Programming\\Jazzy/g
s/JAZZYDICT/f:\\programming\\dict/g
}
